import { User, Post, Story, Reel, ChatMessage, NotificationItem } from './types';
import { generateSvgDataUrl } from './utils/mediaUtils';

export const CURRENT_USER: User = {
  id: 'user_me',
  username: 'souturbo',
  name: 'Sou Turbo ⚡',
  avatar: generateSvgDataUrl('avatar', 'Sou Turbo'),
  bio: 'Criando o futuro da web social ✨ | Fotografia, Tech, Cinema & Conexão Real 🎬🎧',
  website: 'auragram.app/@souturbo',
  followersCount: 14200,
  followingCount: 384,
  postsCount: 12,
  isVerified: true,
  isFollowing: false,
  isOnline: true,
};

export const CONTACTS: User[] = [
  {
    id: 'user_1',
    username: 'gabriela_style',
    name: 'Gabriela Rocha',
    avatar: generateSvgDataUrl('avatar', 'Gabriela Rocha'),
    bio: 'Estilo autoral & Direção criativa em Milão e SP ✨ Representada pela @fordmodels',
    followersCount: 84300,
    followingCount: 512,
    postsCount: 142,
    isVerified: true,
    isFollowing: true,
    isOnline: true,
  },
  {
    id: 'user_2',
    username: 'lucas_lens',
    name: 'Lucas Silva',
    avatar: generateSvgDataUrl('avatar', 'Lucas Silva'),
    bio: 'National Geographic Explorer 🏔️ Caçador de auroras e horizontes infinitos',
    followersCount: 129000,
    followingCount: 219,
    postsCount: 310,
    isVerified: true,
    isFollowing: true,
    isOnline: true,
  },
  {
    id: 'user_3',
    username: 'maya_tech',
    name: 'Maya Santos',
    avatar: generateSvgDataUrl('avatar', 'Maya Santos'),
    bio: 'AI Engineer & Creative Technologist 🦾 Construindo interfaces do amanhã',
    followersCount: 43200,
    followingCount: 401,
    postsCount: 88,
    isVerified: true,
    isFollowing: true,
    isOnline: false,
  },
  {
    id: 'user_4',
    username: 'bruno_beats',
    name: 'Bruno Beats',
    avatar: generateSvgDataUrl('avatar', 'Bruno Beats'),
    bio: 'Music Producer & Sound Designer 🎹 Sintetizadores analógicos & vibes do amanhecer',
    followersCount: 65100,
    followingCount: 690,
    postsCount: 204,
    isVerified: false,
    isFollowing: false,
    isOnline: true,
  },
  {
    id: 'user_5',
    username: 'camila_chef',
    name: 'Camila Ferraz',
    avatar: generateSvgDataUrl('avatar', 'Camila Ferraz'),
    bio: 'Chef executiva & Sommelier de café especial ☕ São Paulo • Paris',
    followersCount: 38900,
    followingCount: 310,
    postsCount: 175,
    isVerified: false,
    isFollowing: true,
    isOnline: false,
  },
];

export const INITIAL_STORIES: Story[] = [
  {
    id: 'story_1',
    author: CONTACTS[0],
    mediaUrl: generateSvgDataUrl('portrait', 'Fashion Week Backstage'),
    mediaType: 'image',
    textSticker: '✨ Ensaio finalizado em Milão!',
    filter: 'clarendon',
    createdAt: 'há 2 horas',
    isSeen: false,
  },
  {
    id: 'story_2',
    author: CONTACTS[1],
    mediaUrl: generateSvgDataUrl('landscape', 'Alps Sunrise Expedition'),
    mediaType: 'image',
    textSticker: 'Subida às 04:30 valeu a pena 🏔️',
    filter: 'valencia',
    createdAt: 'há 4 horas',
    isSeen: false,
  },
  {
    id: 'story_3',
    author: CONTACTS[2],
    mediaUrl: generateSvgDataUrl('urban', 'Shinjuku Cyber Lights'),
    mediaType: 'image',
    textSticker: 'Código + Chuva em Tóquio 💻🌧️',
    filter: 'cyberpunk',
    createdAt: 'há 6 horas',
    isSeen: false,
  },
  {
    id: 'story_4',
    author: CONTACTS[3],
    mediaUrl: generateSvgDataUrl('abstract', 'Modular Synth Jam Session'),
    mediaType: 'image',
    textSticker: 'Novo álbum saindo do forno 🎧',
    filter: 'ludwig',
    createdAt: 'há 8 horas',
    isSeen: false,
  },
  {
    id: 'story_5',
    author: CONTACTS[4],
    mediaUrl: generateSvgDataUrl('cafe', 'Artisan V60 Pour-over'),
    mediaType: 'image',
    textSticker: 'Notas de jasmim e pêssego ☕',
    filter: 'slumber',
    createdAt: 'há 11 horas',
    isSeen: false,
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post_1',
    author: CONTACTS[1],
    mediaUrl: generateSvgDataUrl('landscape', 'Amanhecer nos Andes'),
    mediaType: 'image',
    filter: 'cinematic',
    caption: 'Primeiros raios cortando as nuvens a 4.200 metros. A imensidão aqui ensina o silêncio que a cidade nos tira. Qual foi a última vez que você viu o nascer do sol de verdade? 🏔️✨ #expedicao #fotografia #natureza',
    location: 'Cordilheira dos Andes, Chile',
    musicTrack: 'Ludovico Einaudi • Experience',
    likesCount: 14820,
    isLiked: false,
    commentsCount: 382,
    comments: [
      {
        id: 'c1',
        userId: 'user_1',
        username: 'gabriela_style',
        userAvatar: generateSvgDataUrl('avatar', 'Gabriela Rocha'),
        text: 'Surreal essa luz Lucas!! Parabéns pelo clique 👏',
        createdAt: 'há 1 hora',
        likesCount: 34,
        isLiked: true,
      },
      {
        id: 'c2',
        userId: 'user_me',
        username: 'souturbo',
        userAvatar: CURRENT_USER.avatar,
        text: 'Cores cinematográficas! Qual abertura você usou?',
        createdAt: 'há 45 min',
        likesCount: 12,
        isLiked: false,
      }
    ],
    isSaved: false,
    createdAt: 'há 3 horas',
    tags: ['fotografia', 'natureza', 'aventura', 'andes'],
  },
  {
    id: 'post_2',
    author: CONTACTS[2],
    mediaUrl: generateSvgDataUrl('urban', 'Tóquio Meia Noite'),
    mediaType: 'image',
    filter: 'cyberpunk',
    caption: 'Quando a chuva cai em Shibuya, cada poça de água vira um espelho de neon e futuro. Testando novos sensores de captura noturna em 60fps 🌧️⚡',
    location: 'Shibuya Crossing, Tokyo',
    musicTrack: 'Kavinsky • Nightcall',
    likesCount: 22400,
    isLiked: true,
    commentsCount: 512,
    comments: [
      {
        id: 'c3',
        userId: 'user_4',
        username: 'bruno_beats',
        userAvatar: generateSvgDataUrl('avatar', 'Bruno Beats'),
        text: 'A trilha perfeita pra esse visual 🔥🔥',
        createdAt: 'há 2 horas',
        likesCount: 56,
        isLiked: false,
      }
    ],
    isSaved: true,
    createdAt: 'há 5 horas',
    tags: ['tech', 'tokyo', 'cyberpunk', 'neon'],
  },
  {
    id: 'post_3',
    author: CONTACTS[4],
    mediaUrl: generateSvgDataUrl('cafe', 'Ritual do Café Especial'),
    mediaType: 'image',
    filter: 'valencia',
    caption: 'Grão Catuaí Vermelho fermentado anaerobicamente por 72h. O aroma encheu o estúdio inteiro antes mesmo da primeira extração. Bom dia para quem não começa sem café! ☕💛',
    location: 'Pinheiros, São Paulo',
    musicTrack: 'FKJ • Ylang Ylang',
    likesCount: 7890,
    isLiked: false,
    commentsCount: 164,
    comments: [],
    isSaved: false,
    createdAt: 'há 8 horas',
    tags: ['cafe', 'gastronomia', 'saopaulo', 'lifestyle'],
  },
  {
    id: 'post_4',
    author: CONTACTS[0],
    mediaUrl: generateSvgDataUrl('portrait', 'Alta Costura 2026'),
    mediaType: 'image',
    filter: 'clarendon',
    caption: 'Geometria têxtil & luz direta. Um novo conceito que une sustentabilidade com linhas fluidas. Grata a todo o time maravilhoso desse editorial 🤍',
    location: 'Duomo di Milano, Itália',
    musicTrack: 'Peggy Gou • (It Goes Like) Nanana',
    likesCount: 31200,
    isLiked: false,
    commentsCount: 689,
    comments: [],
    isSaved: false,
    createdAt: 'ontem',
    tags: ['moda', 'fashion', 'editorial', 'milao'],
  }
];

export const INITIAL_REELS: Reel[] = [
  {
    id: 'reel_1',
    author: CONTACTS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    caption: 'Descida insana na neve virgem das montanhas! Sensação de voar 🏂❄️ #snowboard #adrenalina #alpes',
    musicTrack: 'The Weeknd • Blinding Lights (Speed Up)',
    likesCount: 45200,
    isLiked: true,
    commentsCount: 1240,
    comments: [
      {
        id: 'rc1',
        userId: 'user_3',
        username: 'maya_tech',
        userAvatar: generateSvgDataUrl('avatar', 'Maya Santos'),
        text: 'A estabilização dessa câmera tá de outro planeta!',
        createdAt: 'há 1 hora',
        likesCount: 88,
        isLiked: true,
      }
    ],
    isSaved: true,
    sharesCount: 3410,
    tags: ['snowboard', 'esportes', 'inverno', 'viagem'],
  },
  {
    id: 'reel_2',
    author: CONTACTS[3],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    caption: 'Criando um drop no sintetizador analógico Moog em 60 segundos! O que acharam desse bass? 🎛️⚡',
    musicTrack: 'Bruno Beats • Analog Drift 2026',
    likesCount: 68100,
    isLiked: false,
    commentsCount: 2310,
    comments: [],
    isSaved: false,
    sharesCount: 8900,
    tags: ['musica', 'produtor', 'synth', 'studio'],
  },
  {
    id: 'reel_3',
    author: CONTACTS[2],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    caption: 'A beleza escondida nas tempestades elétricas no litoral. A mãe natureza dando um show de eletricidade pura ⚡🌊',
    musicTrack: 'Hans Zimmer • Time (Cinematic Remix)',
    likesCount: 92400,
    isLiked: false,
    commentsCount: 3100,
    comments: [],
    isSaved: false,
    sharesCount: 14200,
    tags: ['natureza', 'tempestade', 'slowmotion', 'cinematic'],
  }
];

export const INITIAL_MESSAGES: Record<string, ChatMessage[]> = {
  user_1: [
    {
      id: 'm1',
      senderId: 'user_1',
      recipientId: 'user_me',
      type: 'text',
      content: 'Oi Turbo! Tudo bem? Vi as novidades no seu perfil!',
      timestamp: '14:10',
      read: true,
    },
    {
      id: 'm2',
      senderId: 'user_me',
      recipientId: 'user_1',
      type: 'text',
      content: 'Opa Gabi! Tudo ótimo por aqui! Acabei de lançar o novo app social com chamadas em vídeo e áudio em tempo real ✨',
      timestamp: '14:12',
      read: true,
    },
    {
      id: 'm3',
      senderId: 'user_1',
      recipientId: 'user_me',
      type: 'text',
      content: 'Nossa que incrível!! Me liga em vídeo rapidinho pra eu ver a qualidade da câmera? 📹😍',
      timestamp: '14:15',
      read: false,
    }
  ],
  user_2: [
    {
      id: 'm4',
      senderId: 'user_2',
      recipientId: 'user_me',
      type: 'text',
      content: 'Fala Turbo! Já cheguei na base dos Andes, a internet via satélite tá voando!',
      timestamp: '11:30',
      read: true,
    },
    {
      id: 'm5',
      senderId: 'user_me',
      recipientId: 'user_2',
      type: 'text',
      content: 'Show de bola Lucas! Bora fazer uma chamada de voz quando tiver um tempo livre?',
      timestamp: '11:42',
      read: true,
    }
  ]
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n1',
    user: CONTACTS[0],
    type: 'like',
    content: 'curtiu sua publicação recente.',
    createdAt: 'há 10 min',
    read: false,
  },
  {
    id: 'n2',
    user: CONTACTS[2],
    type: 'comment',
    content: 'comentou: "Trabalho sensacional meu amigo!"',
    createdAt: 'há 35 min',
    read: false,
  },
  {
    id: 'n3',
    user: CONTACTS[3],
    type: 'follow',
    content: 'começou a seguir você.',
    createdAt: 'há 2 horas',
    read: true,
  },
  {
    id: 'n4',
    user: CONTACTS[1],
    type: 'mention',
    content: 'mencionou você em um comentário: "@souturbo confere isso"',
    createdAt: 'ontem',
    read: true,
  }
];
